[package]
name = "quantum-animal-shogi-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
arrayvec = "0"
itertools = "0"
nalgebra = "0"
ndarray = "0"
num-traits = "0"
unicode-width = "0"
