[package]
name = "quantum-animal-shogi-python"
version = "0.1.0"
edition = "2024"

[lib]
name = "quantum_animal_shogi"
crate-type = ["cdylib"]

[dependencies]
itertools = "0"
nalgebra = "0"
ndarray = "0"
numpy = "0"
pyo3 = "0"
quantum-animal-shogi-core = { path = "../core" }
