[package]
name = "quantum-animal-shogi"
version = "0.1.0"
edition = "2024"

[lib]
name = "quantum_animal_shogi"
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.7.6"
itertools = "0.14.0"
ndarray = "0.17.1"
num-traits = "0.2.19"
numpy = "0.27.1"
pyo3 = "0.27.0"
unicode-width = "0.2.2"
